FROM python:3.10-slim

WORKDIR /app

COPY requirements-bot.txt .
RUN pip install --no-cache-dir -r requirements-bot.txt

COPY *.py .

CMD ["uvicorn", "bot_logic:app", "--host", "0.0.0.0", "--port", "5000"]
