FROM python:3.10-slim

WORKDIR /app

ENV ADMIN_REPORT_NUMBER=584242268245

COPY requirements-bot.txt .
RUN pip install --no-cache-dir -r requirements-bot.txt

COPY *.py .

CMD ["uvicorn", "bot_presentation:app", "--host", "0.0.0.0", "--port", "5000"]
